//===- PlanReport.h - Versioned JSON plan report (design §22.2) -----------===//
//
// Part of the target-independent mapping core (epic #67, workstream D7).
//
// A plan report is reproducibility and diagnostic metadata, never executable
// input: it names the exact inputs a search ran on -- the module hash, the
// machine, the layout and rule libraries, and the source search binding -- the
// options it used, how far it got, and the plans it retained with their costs.
// The binding is reported self-containedly: its `micro.candidate` symbol, its
// sorted parameter values, and its content hash, so a consumer holding only the
// report can re-run the search at the same `candidate=` and reproduce the plan
// ids (a binding-derived id is only reproducible at the same search point).
// It does not replace `micro.search_space` or the bound Micro-IR.
//
// Determinism is the contract (design §29.12): two runs with identical inputs
// must emit byte-identical JSON. Keys are written in a fixed order (the report
// is built imperatively, so `llvm::json`'s internally unordered object never
// reaches the output), and no timestamp, address, or unordered iteration is
// included. Costs render through `canonicalCostString` / a fixed `%.6f`, both
// byte-stable across runs and platforms.
//
//===----------------------------------------------------------------------===//

#ifndef LLK_MAPPING_PLANREPORT_H
#define LLK_MAPPING_PLANREPORT_H

#include "LLK/Machine/MachineModel.h"
#include "LLK/Mapping/CoveringSearch.h"
#include "LLK/Mapping/MappingTarget.h"
#include "LLK/Mapping/WorkloadGraph.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"

#include <cstdint>
#include <string>

namespace mlir::llk::mapping {

/// The report schema version. A reader keys its parser on it; a compatible
/// addition of a field does not change the version, but a change to an existing
/// field's meaning does. Version 2 folds endpoint occurrences into
/// `canonicalConnectionString` / `canonicalCandidateString`, which changed the
/// meaning -- and therefore the printed values -- of every plan and connection
/// id, so ids written under version 1 must not be replayed under these
/// semantics.
inline constexpr uint64_t kPlanReportVersion = 2;

/// The compiler version the report was produced by (design §22.2): the project
/// version plus a `git describe` suffix, generated by CMake into
/// `LLK/Version.h` (see `include/LLK/Version.h.in`). It is a real version, so
/// two compiler revisions never print identically. The cost-model version is
/// `kCostModelVersion` (LatencyProvider.h), the same value a measurement's
/// cache key carries.
llvm::StringRef compilerVersion();

/// Serializes `result` to the versioned JSON plan report. `moduleHash` is the
/// content hash of the input module the search ran over (the caller computes it
/// before any binding mutates the module). The returned string is byte-stable
/// for identical inputs.
std::string writePlanReport(const MappingSearchResult &result,
                            const machine::MachineModel &machine,
                            const MappingTarget &target,
                            const MappingSearchOptions &options,
                            uint64_t moduleHash);

/// Writes `writePlanReport(...)` to `path`, creating or truncating it. Returns
/// an error the caller reports rather than silently dropping the report.
llvm::Error writePlanReportFile(llvm::StringRef path,
                                const MappingSearchResult &result,
                                const machine::MachineModel &machine,
                                const MappingTarget &target,
                                const MappingSearchOptions &options,
                                uint64_t moduleHash);

/// Reconstructs the selected plan a v2 report recorded, so a caller holding the
/// report and the exact target and source workload graph can replay the
/// selection (task B1). This reconstructs *data*, not executable code: semantic
/// verification and materialization remain mandatory, and both content hashes
/// are validated first -- the report's `graphHash` must match
/// `computeSourceGraphHash(graph)` and its `targetHash` must match `target`, so
/// a semantically-changed input graph or a different target is rejected before
/// any executable binding. Every recorded placement must also still resolve in
/// `graph`. A report written by a different schema version is rejected.
///
/// NOTE: the returned plan does *not* carry context-bound `mlir::AffineMap`s
/// (a solved layout's concrete map or a transform's maps). An `AffineMap` is
/// owned by an `MLIRContext`, and this function has none that outlives the
/// call, so a map parsed into a temporary context would dangle. The report
/// still records every map in its printed form; a caller that needs the maps
/// (C5) must re-derive them from the recorded parameters and the layout
/// declaration (and re-validate them), exactly as `decodeSelectedPlan` does
/// against a live module.
///
/// RANKING SCORE (stage C, task C5): a report-replayed plan carries *no*
/// ranking score. The report records no `totalCost`/`accumulatedCost`, no
/// `scoreSource`, and none of the derived execution facts `buildPlanEvents`
/// charges -- each placement's `cost`/`workItems`, each connection's
/// `cost`/`valueType` -- so `buildPlanEvents` rejects the replayed plan
/// (`plan.schemaVersion != 0` with zero-cost placements) and any ranking over
/// it would see cost 0. This is deliberate: inventing score facts here would
/// let a replay claim a scheduled latency it never measured. A caller that
/// needs to rank or bind a replayed plan must **re-score** it first -- re-run
/// the search that produced it (or otherwise rebuild the plan's normalized
/// events through `buildPlanEvents` + `schedulePlanEvents`) before calling
/// `ranksBefore`. Replay-and-rank is a C5 deliverable, not satisfied by this
/// reader.
llvm::Expected<CoveringPlan> readPlanReport(llvm::StringRef json,
                                            const MappingTarget &target,
                                            const WorkloadGraph &graph);

} // namespace mlir::llk::mapping

#endif // LLK_MAPPING_PLANREPORT_H
